# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Anas KHABALI
email: anas.khabali@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Je suis Anas KHABALI, un artisan du logiciel,
  fasciné par les langages de programmation, les systèmes d'information et l'intégration des données.
  Et sur ce site, je vais documenter les sujets que j'apprends, faire des résumés de ma veille technologique,
  vous présentez mes projets personnels et d'autres choses divers et variées.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://khabali.github.io" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: anas_khabali
github_username:  khabali
linkedin_username : anaskhabali

# URL of your avatar or profile pic
author_avatar: https://avatars1.githubusercontent.com/u/1675609
repository: khabali/khabali.github.io
github_repo: https://github.com/khabali/khabali.github.io

google_analytics_id : ""

# Build settings
markdown: kramdown
#theme: minima
gems:
  - jekyll-feed
  - jekyll-redirect-from
  - jemoji
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-avatar
  - jekyll-mentions

exclude:
  - README.md
  - .gitignore
